=== BreisOne/daw-notes/DWLM/Eval1/Tema2-XSD/Tareas/Tarefa2/tarefa3b.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    
    <!-- Definición del tipo para duración -->
    <xs:element name="duracion">
        <xs:complexType>
            <xs:attribute name="horas">
                <xs:simpleType>
                    <xs:restriction base="xs:integer">
                        <xs:minInclusive value="0"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="sesions">
                <xs:simpleType>
                    <xs:restriction base="xs:integer">
                        <xs:minInclusive value="0"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="sesionsSemanais">
                <xs:simpleType>
                    <xs:restriction base="xs:integer">
                        <xs:minInclusive value="0"/>
                        <xs:maxInclusive value="21"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>

    <!-- Definición del elemento ciclo -->
    <xs:element name="ciclo">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="tipoNomeLongo">
                    <xs:attribute name="codigo" type="tipoCodigoCiclo" use="required" />
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>

    <!-- Definición del elemento UD -->
    <xs:element name="UD">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="titulo" type="tipoNomeLongo" />
                <xs:element name="descrición" type="xs:string" minOccurs="0" />
            </xs:sequence>
            <xs:attribute name="num" type="xs:integer" use="required" />
            <xs:attribute name="sesións" type="xs:integer" use="required" />
        </xs:complexType>
    </xs:element>

    <!-- Definición del elemento contidos -->
    <xs:element name="contidos">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="UD" maxOccurs="21"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- Elemento principal modulo -->
    <xs:element name="modulo">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="duracion"/>
                <xs:element name="nome" type="xs:string" />
                <xs:element ref="ciclo" maxOccurs="unbounded"/>
                <xs:element ref="contidos"/>
            </xs:sequence>
            <xs:attribute name="codigo">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="[M][P][0-9]{3}"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="tipoNomeLongo">
        <xs:restriction base="xs:string">
            <xs:maxLength value="150"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="tipoCodigoCiclo">
        <xs:restriction base="xs:string">
            <xs:pattern value="[C][SM][A-Z]{3}\d{2}"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== BreisOne/daw-notes/DWLM/Eval1/Tema2-XSD/Tareas/Tarefa2/tarefa3b.xml
<?xml version="1.0" encoding="UTF-8"?>
<modulo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="tarefa3b.xsd" codigo="MP373">

    <duracion horas="133" sesions="160" sesionsSemanais="5" />
    <nome>Linguaxes de marcas e sistemas de xestión da información</nome>
    <ciclo codigo="CSIFC01">Administración de sistemas informáticos e redes</ciclo>
    <ciclo codigo="CSIFC02">Desenvolvemento de aplicacións multiplataforma</ciclo>
    <ciclo codigo="CSIFC03">Desenvolvemento de aplicacións web</ciclo>
    <contidos>
        <UD num="1" sesións="5">
            <titulo>
                Aplicacións web. Introdución aos linguaxes de marcas
            </titulo>
            <descrición>
                Introdución aos conceptos relacionados coas aplicacións web.
                Páxinas web estáticas e dinámicas. Introdución aos linguaxes
                de marcas.
            </descrición>
        </UD>
        <UD num="2" sesións="12">
            <titulo>
                Linguaxes de marcas para a transmisión de información a
                Páxina 29 de 40 través da Web: HTML.
            </titulo>
        </UD>
        <UD num="3" sesións="13">
            <titulo>
                Linguaxes de marcas para a transmisión de información a
                través da Web: CSS
            </titulo>
            <descrición>
                Separar o contido da presentación. Follas de estilo CSS.
            </descrición>
        </UD>
    </contidos>
</modulo>
