=== BreisOne/daw-notes/DWLM/Eval1/Tema2-XSD/Tareas/Tarefa2/tarefa3a.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="garderia">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="neno" minOccurs="1" maxOccurs="50"
                    type="tipoNeno" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="tipoNeno">
        <xs:sequence>
            <xs:element name="nome" type="xs:string" />
            <xs:element name="dataNacemento" type="xs:date" />
            <xs:element ref="peso"/>
            <xs:element name="altura" type="xs:unsignedByte" />
            <xs:element ref="sexo"/>
            <xs:element name="vacunas" type="xs:boolean" />
            <xs:element ref="contacto" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="numeroExpedente" type="xs:unsignedShort" />
        <xs:attribute name="codigo">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:pattern value="[PM][3-7][3-7](-[0-9]{3})?"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>

    <!-- Definición do elemento sexo -->
    <xs:element name="sexo">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="M" />
                <xs:enumeration value="F" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <!-- Definición do elemento peso -->
    <xs:element name="peso">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                <xs:fractionDigits value="1"/>
                <xs:minInclusive value="0.1"/>
                <xs:totalDigits value="4"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <!-- Definición do elemento contacto -->
    <xs:element name="contacto">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:pattern value="[0-9]{9}"/>
            </xs:restriction>
        </xs:simpleType>
        <xs:attribute name="relacion" type="xs:string">
            <xs:simpleType>
                <xs:restriction base="xs:string"></xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:element>
</xs:schema>

=== BreisOne/daw-notes/DWLM/Eval1/Tema2-XSD/Tareas/Tarefa2/tarefa3a.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- tarefa 1 UD7 -->
<garderia xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="tarefa3a.xsd">
    <neno numeroExpedente="2344">
        <nome>Noa Blanco Coello</nome>
        <dataNacemento>2010-10-12</dataNacemento>
        <peso>13.5</peso>
        <altura>78</altura>
        <sexo>F</sexo>
        <vacunas>true</vacunas>
    </neno>
</garderia>
